CXXFLAGS += -O2
CXXFLAGS += -Wall
CXXFLAGS += -Wextra
CXXFLAGS += -pedantic
CXXFLAGS += -Weffc++
CXXFLAGS += -std=c++17
#CXXFLAGS += -Werror
CXXFLAGS += --all-warnings
CXXFLAGS += --extra-warnings
CXXFLAGS += -W
CXXFLAGS += -Wno-abi-tag
CXXFLAGS += -Waddress
CXXFLAGS += -Waddress-of-packed-member
CXXFLAGS += -Wno-aggregate-return
CXXFLAGS += -Waggressive-loop-optimizations
CXXFLAGS += -Waligned-new=all
CXXFLAGS += -Walloc-zero
CXXFLAGS += -Walloca
CXXFLAGS += -Warray-bounds
CXXFLAGS += -Warray-bounds=2
CXXFLAGS += -Wattribute-alias=2
CXXFLAGS += -Wattribute-warning
CXXFLAGS += -Wattributes
CXXFLAGS += -Wbool-compare
CXXFLAGS += -Wbool-operation
CXXFLAGS += -Wbuiltin-declaration-mismatch
CXXFLAGS += -Wbuiltin-macro-redefined
CXXFLAGS += -Wc++0x-compat
CXXFLAGS += -Wc++11-compat
CXXFLAGS += -Wc++14-compat
CXXFLAGS += -Wc++17-compat
CXXFLAGS += -Wc++1z-compat
CXXFLAGS += -Wcannot-profile
CXXFLAGS += -Wcast-align
CXXFLAGS += -Wcast-align=strict
CXXFLAGS += -Wcast-function-type
CXXFLAGS += -Wcast-qual
CXXFLAGS += -Wcatch-value=3
CXXFLAGS += -Wchar-subscripts
CXXFLAGS += -Wclass-conversion
CXXFLAGS += -Wclass-memaccess
CXXFLAGS += -Wclobbered
CXXFLAGS += -Wcomment
CXXFLAGS += -Wcomments
CXXFLAGS += -Wconditionally-supported
CXXFLAGS += -Wconversion
CXXFLAGS += -Wconversion-null
CXXFLAGS += -Wcoverage-mismatch
CXXFLAGS += -Wcpp
CXXFLAGS += -Wctor-dtor-privacy
CXXFLAGS += -Wdangling-else
CXXFLAGS += -Wdate-time
CXXFLAGS += -Wdelete-incomplete
CXXFLAGS += -Wdelete-non-virtual-dtor
CXXFLAGS += -Wdeprecated
CXXFLAGS += -Wdeprecated-copy
CXXFLAGS += -Wdeprecated-copy-dtor
CXXFLAGS += -Wdeprecated-declarations
CXXFLAGS += -Wdisabled-optimization
CXXFLAGS += -Wdiv-by-zero
CXXFLAGS += -Wdouble-promotion
CXXFLAGS += -Wduplicated-branches
CXXFLAGS += -Wduplicated-cond
CXXFLAGS += -Wempty-body
CXXFLAGS += -Wendif-labels
CXXFLAGS += -Wenum-compare
CXXFLAGS += -Wexpansion-to-defined
CXXFLAGS += -Wfloat-conversion
CXXFLAGS += -Wfloat-equal
CXXFLAGS += -Wformat -Wformat-contains-nul
CXXFLAGS += -Wformat -Wformat-extra-args
CXXFLAGS += -Wformat -Wformat-nonliteral
CXXFLAGS += -Wformat -Wformat-security
CXXFLAGS += -Wformat -Wformat-y2k
CXXFLAGS += -Wformat -Wformat-zero-length
CXXFLAGS += -Wformat-overflow=2
CXXFLAGS += -Wformat-signedness
CXXFLAGS += -Wformat-truncation=2
CXXFLAGS += -Wformat=2
CXXFLAGS += -Wframe-address
CXXFLAGS += -Wfree-nonheap-object
CXXFLAGS += -Whsa
CXXFLAGS += -Wif-not-aligned
CXXFLAGS += -Wignored-attributes
CXXFLAGS += -Wignored-qualifiers
CXXFLAGS += -Wimplicit-fallthrough=5
CXXFLAGS += -Winherited-variadic-ctor
CXXFLAGS += -Winit-list-lifetime
CXXFLAGS += -Winit-self
#CXXFLAGS += -Winline
CXXFLAGS += -Wint-in-bool-context
CXXFLAGS += -Wint-to-pointer-cast
CXXFLAGS += -Winvalid-memory-model
CXXFLAGS += -Winvalid-offsetof
CXXFLAGS += -Winvalid-pch
CXXFLAGS += -Wliteral-suffix
CXXFLAGS += -Wlogical-not-parentheses
CXXFLAGS += -Wlogical-op
CXXFLAGS += -Wno-long-long
CXXFLAGS += -Wlto-type-mismatch
CXXFLAGS += -Wmain
CXXFLAGS += -Wmaybe-uninitialized
CXXFLAGS += -Wmemset-elt-size
CXXFLAGS += -Wmemset-transposed-args
CXXFLAGS += -Wmisleading-indentation
CXXFLAGS += -Wmissing-attributes
CXXFLAGS += -Wmissing-braces
CXXFLAGS += -Wno-missing-declarations
CXXFLAGS += -Wmissing-field-initializers
CXXFLAGS += -Wmissing-include-dirs
CXXFLAGS += -Wmissing-profile
CXXFLAGS += -Wmultichar
#CXXFLAGS += -Wmultiple-inheritance
CXXFLAGS += -Wmultistatement-macros
CXXFLAGS += -Wno-namespaces
CXXFLAGS += -Wnarrowing
CXXFLAGS += -Wno-noexcept
CXXFLAGS += -Wnoexcept-type
CXXFLAGS += -Wnon-template-friend
CXXFLAGS += -Wnon-virtual-dtor
CXXFLAGS += -Wnonnull
CXXFLAGS += -Wnonnull-compare
CXXFLAGS += -Wnormalized=nfkc
CXXFLAGS += -Wnull-dereference
CXXFLAGS += -Wodr
CXXFLAGS += -Wold-style-cast
CXXFLAGS += -Wopenmp-simd
CXXFLAGS += -Woverflow
CXXFLAGS += -Woverlength-strings
CXXFLAGS += -Woverloaded-virtual
CXXFLAGS += -Wpacked
CXXFLAGS += -Wpacked-bitfield-compat
CXXFLAGS += -Wpacked-not-aligned
CXXFLAGS += -Wno-padded
CXXFLAGS += -Wparentheses
CXXFLAGS += -Wpedantic
CXXFLAGS += -Wpessimizing-move
CXXFLAGS += -Wplacement-new=2
CXXFLAGS += -Wpmf-conversions
CXXFLAGS += -Wpointer-arith
CXXFLAGS += -Wpointer-compare
CXXFLAGS += -Wpragmas
CXXFLAGS += -Wprio-ctor-dtor
CXXFLAGS += -Wpsabi
CXXFLAGS += -Wredundant-decls
CXXFLAGS += -Wredundant-move
CXXFLAGS += -Wregister
CXXFLAGS += -Wreorder
CXXFLAGS += -Wrestrict
CXXFLAGS += -Wreturn-local-addr
CXXFLAGS += -Wreturn-type
CXXFLAGS += -Wscalar-storage-order
CXXFLAGS += -Wsequence-point
CXXFLAGS += -Wshadow=compatible-local
CXXFLAGS += -Wshadow=global
CXXFLAGS += -Wshadow=local
CXXFLAGS += -Wshift-count-negative
CXXFLAGS += -Wshift-count-overflow
CXXFLAGS += -Wshift-negative-value
CXXFLAGS += -Wshift-overflow=2
CXXFLAGS += -Wsign-compare
CXXFLAGS += -Wsign-conversion
CXXFLAGS += -Wsign-promo
CXXFLAGS += -Wsized-deallocation
CXXFLAGS += -Wsizeof-array-argument
CXXFLAGS += -Wsizeof-pointer-div
CXXFLAGS += -Wsizeof-pointer-memaccess
CXXFLAGS += -Wstack-protector
CXXFLAGS += -Wstrict-aliasing
CXXFLAGS += -Wstrict-aliasing=3
CXXFLAGS += -Wstrict-null-sentinel
CXXFLAGS += -Wstrict-overflow
CXXFLAGS += -Wstrict-overflow=5
CXXFLAGS += -Wstringop-overflow
CXXFLAGS += -Wstringop-overflow=4
CXXFLAGS += -Wstringop-truncation
CXXFLAGS += -Wsubobject-linkage
CXXFLAGS += -Wsuggest-attribute=cold
CXXFLAGS += -Wsuggest-attribute=const
CXXFLAGS += -Wsuggest-attribute=format
CXXFLAGS += -Wsuggest-attribute=malloc
CXXFLAGS += -Wsuggest-attribute=noreturn
CXXFLAGS += -Wsuggest-attribute=pure
CXXFLAGS += -Wsuggest-final-methods
CXXFLAGS += -Wsuggest-final-types
CXXFLAGS += -Wsuggest-override
CXXFLAGS += -Wswitch
CXXFLAGS += -Wswitch-bool
CXXFLAGS += -Wswitch-default
CXXFLAGS += -Wno-switch-enum
CXXFLAGS += -Wswitch-unreachable
CXXFLAGS += -Wsync-nand
CXXFLAGS += -Wsynth
CXXFLAGS += -Wno-system-headers
CXXFLAGS += -Wtautological-compare
CXXFLAGS += -Wno-templates
CXXFLAGS += -Wterminate
CXXFLAGS += -Wtrampolines
CXXFLAGS += -Wtrigraphs
CXXFLAGS += -Wtype-limits
CXXFLAGS += -Wundef
CXXFLAGS += -Wuninitialized
CXXFLAGS += -Wunknown-pragmas
CXXFLAGS += -Wunreachable-code
CXXFLAGS += -Wunsafe-loop-optimizations
CXXFLAGS += -Wunused
CXXFLAGS += -Wunused-but-set-parameter
CXXFLAGS += -Wunused-but-set-variable
CXXFLAGS += -Wunused-const-variable=2
CXXFLAGS += -Wunused-function
CXXFLAGS += -Wunused-label
CXXFLAGS += -Wno-unused-local-typedefs
CXXFLAGS += -Wunused-macros
CXXFLAGS += -Wunused-parameter
CXXFLAGS += -Wunused-result
CXXFLAGS += -Wunused-value
CXXFLAGS += -Wunused-variable
CXXFLAGS += -Wuseless-cast
CXXFLAGS += -Wvarargs
CXXFLAGS += -Wvariadic-macros
CXXFLAGS += -Wvector-operation-performance
CXXFLAGS += -Wvirtual-inheritance
CXXFLAGS += -Wvirtual-move-assign
CXXFLAGS += -Wvla
CXXFLAGS += -Wvolatile-register-var
CXXFLAGS += -Wwrite-strings
CXXFLAGS += -Wzero-as-null-pointer-constant


OBJDIR = ./obj

FILES = $(wildcard *.cpp)

.PHONY: all
.PHONY: a
.PHONY: c
.PHONY: i
.PHONY: k
.PHONY: l
.PHONY: s

all: a c i k l s

a:
	${CXX} -c asmstream.cpp -o ${OBJDIR}/asmstream.o ${CXXFLAGS}

c:
	${CXX} -c cppasm.cpp -o ${OBJDIR}/cppasm.o ${CXXFLAGS}

i:
	${CXX} -c Instruction.cpp -o ${OBJDIR}/Instruction.o ${CXXFLAGS}

k:
	${CXX} -c keyword.cpp -o ${OBJDIR}/keyword.o ${CXXFLAGS}

l:
	${CXX} -c label.cpp -o ${OBJDIR}/label.o ${CXXFLAGS}

s:
	${CXX} -c streamdest_cout.cpp -o ${OBJDIR}/streamdest_cout.o ${CXXFLAGS}
	${CXX} -c section.cpp -o ${OBJDIR}/section.o ${CXXFLAGS}
	${CXX} -c st.cpp -o ${OBJDIR}/st.o ${CXXFLAGS}

syntax:
	${CXX} -fsyntax-only ${FILES} ${CXXFLAGS}
